packages:
  - "."

onlyBuiltDependencies:
  - esbuild

ignoredBuiltDependencies:
  - "@vscode/vsce-sign"
  - keytar
allowBuilds:
  '@vscode/vsce-sign': false
  core-js: false
  esbuild: true
  keytar: false
